# Generated by Django 5.0.6 on 2026-06-20 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_entity_tally_company_name_entity_zoho_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payment_blocked', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='entities.entity')),
            ],
            options={
                'unique_together': {('entity', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VendorRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
                ('exception_count_90d', models.PositiveIntegerField(default=0)),
                ('avg_resolution_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('sla_breach_count', models.PositiveIntegerField(default=0)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
