# Generated by Django 5.0.6 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tally_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='zoho_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='zoho_org_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='zoho_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='zoho_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
