# Generated by Django 5.0.6 on 2026-06-20 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_entity_tally_company_name_entity_zoho_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_gstr2b', models.PositiveIntegerField(default=0)),
                ('total_purchase', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('exceptions', models.PositiveIntegerField(default=0)),
                ('itc_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_runs', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSTR2BRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_period', models.CharField(max_length=7)),
                ('supplier_gstin', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_records', to='entities.entity')),
            ],
            options={
                'unique_together': {('entity', 'tax_period', 'supplier_gstin', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_period', models.CharField(max_length=7)),
                ('supplier_gstin', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_entries', to='entities.entity')),
            ],
            options={
                'unique_together': {('entity', 'tax_period', 'supplier_gstin', 'invoice_number')},
            },
        ),
    ]
