# Generated by Django 5.0.6 on 2026-06-20 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_entity_tally_company_name_entity_zoho_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form26ASEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('quarter', models.CharField(max_length=2)),
                ('deductor_pan', models.CharField(max_length=10)),
                ('deductor_name', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('section_code', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form26as_entries', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TDSLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('quarter', models.CharField(max_length=2)),
                ('deductor_pan', models.CharField(max_length=10)),
                ('deductor_name', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('section_code', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_ledger_entries', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TDSReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('quarter', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_26as', models.PositiveIntegerField(default=0)),
                ('total_ledger', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('exceptions', models.PositiveIntegerField(default=0)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_runs', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
